Repository BlackmoorHold/Blackmoor-hold, pull requests merged in 2025-06, with the labels that each got.

#22 NSFW Headshots and tiny headshot icons on examine
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_topic.dm
Labels: testmerged

#23 less puking more stitching
  code/datums/wounds/types/arteries.dm
  code/modules/mob/living/carbon/human/life.dm
Labels: testmerged

#31 Allows furries to be jesters.
  code/modules/jobs/job_types/roguetown/courtier/jester.dm
Labels: testmerged

#25 running into things dont knockdown
  code/game/objects/structures.dm
  code/game/turfs/closed/_closed.dm
Labels: testmerged

#28 Less bitching for nobles and church virgins
  code/datums/stress/negative_events.dm
Labels: testmerged

#30 Reagent unfuckening
  code/game/objects/items/rogueweapons/ranged/ammo.dm
  code/game/objects/structures/well.dm
  code/modules/farming/produce.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  code/modules/roguetown/roguecrafting/alchemy.dm
  code/modules/roguetown/roguecrafting/alchemy/alch_cauldron_recipes.dm
  code/modules/roguetown/roguecrafting/alchemy/reagents.dm
  code/modules/roguetown/roguecrafting/crafting/ammo_and_ranged.dm
  code/modules/roguetown/roguejobs/alchemist/container.dm
  code/modules/roguetown/roguestock/import.dm
  code/modules/surgery/organs/organ_internal.dm
  modular/Creechers/code/trufflepig.dm
  modular/Neu_Food/code/cooked/cooked_pastry.dm
  modular/Neu_Food/code/cooked/cooked_pies.dm
Labels: testmerged

#26 fill bottles/containers from fountain and taste more frequently
  code/game/objects/structures/well.dm
  code/modules/mob/living/taste.dm
Labels: testmerged

#48 Makes say bar of the chat be used for commands like everywhere else
  interface/skin.dmf
Labels: testmerged

#33 Adds auto mining mineral walls.
  code/game/turfs/closed/minerals.dm
Labels: testmerged

#45 Miracles automatically target and heal the most damaged limb
  code/modules/spells/roguetown/acolyte/general.dm
  modular_azurepeak/code/modules/spells/pantheon/inhumen/matthios.dm
Labels: testmerged

#66 Adds a royal gambeson + fix fancy coat details
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/clothing/rogueclothes/shirts.dm
  code/modules/jobs/job_types/roguetown/nobility/bailiff.dm
  code/modules/jobs/job_types/roguetown/nobility/lady.dm
  code/modules/jobs/job_types/roguetown/nobility/lord.dm
  code/modules/jobs/job_types/roguetown/youngfolk/prince.dm
  icons/roguetown/clothing/armor.dmi
  icons/roguetown/clothing/onmob/armor.dmi
  icons/roguetown/clothing/onmob/helpers/sleeves_armor.dmi
Labels: testmerged

#65 Redmoon port - Family system
  code/__DEFINES/preferences.dm
  code/__DEFINES/roguetown.dm
  code/controllers/subsystem/rogue/family.dm
  code/controllers/subsystem/ticker.dm
  code/datums/sexcon.dm
  code/datums/sexcon/sexcon.dm
  code/game/objects/structures/fluff.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/roguetown/adventurer/bandit.dm
  code/modules/jobs/job_types/roguetown/church/priest.dm
  code/modules/jobs/job_types/roguetown/goblin/chieftain.dm
  code/modules/jobs/job_types/roguetown/goblin/tribalcook.dm
  code/modules/jobs/job_types/roguetown/goblin/tribalguard.dm
  code/modules/jobs/job_types/roguetown/goblin/tribalsmith.dm
  code/modules/jobs/job_types/roguetown/nobility/lady.dm
  code/modules/jobs/job_types/roguetown/nobility/lord.dm
  code/modules/jobs/job_types/roguetown/other/goblin.dm
  code/modules/jobs/job_types/roguetown/peasants/bathmaid.dm
  code/modules/jobs/job_types/roguetown/peasants/beggar.dm
  code/modules/jobs/job_types/roguetown/peasants/bogprisoner.dm
  code/modules/jobs/job_types/roguetown/peasants/hostage.dm
  code/modules/jobs/job_types/roguetown/peasants/lunatic.dm
  code/modules/jobs/job_types/roguetown/peasants/prisoner.dm
  code/modules/jobs/job_types/roguetown/youngfolk/prince.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/examine.dm
  icons/mob/rel.dmi
  modular/memory_for_family_members/memory_for_family_members.dm
  roguetown.dme
  strings/family.json
Labels: testmerged

#86 Change keep colors
  code/__HELPERS/lordcolor.dm
Labels: testmerged

#99 Readds love potions
  code/datums/mind.dm
  code/modules/cargo/packsrogue/merchant/luxury.dm
  code/modules/roguetown/roguecrafting/alchemy/alch_items.dm
Labels: testmerged

#112 Adds Belly Markings to Half-Kin
  code/modules/mob/living/carbon/human/species_types/furry/demihuman.dm
Labels: testmerged

#103 Pillories can be crafted
  code/modules/roguetown/roguecrafting/structure.dm
Labels: testmerged

#117 Godwin Forced Me To Make This
  code/modules/jobs/job_types/roguetown/garrison/manorguard.dm
Labels: testmerged

#88 health pot fix
  code/modules/roguetown/roguecrafting/alchemy/reagents.dm
Labels: testmerged

#92 Revert "Revert "Armorer's Touch: Wrists and Neck edition"" (Other words a hotfix)
  code/modules/cargo/packsrogue/merchant/armor.dm
  code/modules/clothing/rogueclothes/neck.dm
  code/modules/clothing/rogueclothes/wrists.dm
  code/modules/roguetown/roguecrafting/leather/leather_armor_recipes.dm
  code/modules/roguetown/roguecrafting/sewing.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/armor.dm
Labels: testmerged

#107 Skirt and tasset leg coverage.
  code/modules/clothing/rogueclothes/pants.dm
Labels: testmerged

#113 acolytes get enough medicine to reattach limbs
  code/modules/jobs/job_types/roguetown/church/monk.dm
Labels: testmerged

#93 Adds the spellcaster equipment to the loadout
  modular_azurepeak/code/datums/loadout.dm
Labels: testmerged

#119 Ports azure peak transformation and gives druid back beast tame
  code/datums/components/riding.dm
  code/datums/gods/patrons/divine_pantheon.dm
  code/modules/antagonists/roguetown/villain/werewolf/werewolf_transformation.dm
  code/modules/language/roguetown/beast.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/other/werewolf.dm
  code/modules/mob/living/carbon/human/species_types/wildshape/cat.dm
  code/modules/mob/living/carbon/human/species_types/wildshape/saiga.dm
  code/modules/mob/living/carbon/human/species_types/wildshape/spider.dm
  code/modules/mob/living/carbon/human/species_types/wildshape/volf.dm
  code/modules/mob/living/carbon/human/species_types/wildshape/wildshape_transformation.dm
  code/modules/mob/living/simple_animal/animal_defense.dm
  code/modules/spells/roguetown/acolyte/dendor.dm
  code/modules/spells/spell_types/wildshape.dm
  roguetown.dme
Labels: testmerged

#129 Leash code port ***Ready for merge***
  code/datums/migrants/migrant_waves/slaver roles.dm
  code/game/objects/examine.dm
  code/game/objects/items.dm
  code/game/objects/items/rogueitems/leash.dm
  code/game/objects/items/rogueitems/util.dm
  code/modules/cargo/packsrogue/bathmatron/bath_clothes.dm
  code/modules/clothing/rogueclothes/neck.dm
  code/modules/jobs/job_types/roguetown/peasants/bathmaid.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/living.dm
  code/modules/roguetown/roguecrafting/crafting/clothes.dm
  code/modules/roguetown/roguecrafting/crafting/weapons_tools.dm
  code/modules/roguetown/roguecrafting/sewing.dm
  modular/icons/mob/collars_leashes.dmi
  modular/icons/obj/items/leashes_collars.dmi
  modular_azurepeak/code/datums/loadout.dm
  roguetown.dme
Labels: testmerged

#46 Resubmit of #38
  code/game/objects/structures/mineral_doors.dm
Labels: testmerged

#128 noose and gallows
  code/datums/components/rotting.dm
  code/modules/mob/mob_defines.dm
  code/modules/roguetown/roguecrafting/structure.dm
  modular/code/game/objects/gallows.dm
Labels: testmerged

#111 New rites for astrata worshippers
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/datums/status_effects/rogue/roguebuff.dm
  code/modules/mob/living/carbon/damage_procs.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
  datums/status_effects/rogue/roguebuff.dm
  modular_azurepeak/code/game/objects/items/ritualcircles.dm
Labels: testmerged

#100 Ports over emberwine
  code/datums/sexcon/sexcon.dm
  code/datums/sexcon/sexcon_reagents.dm
  code/datums/status_effects/rogue/debuff.dm
  code/modules/cargo/packsrogue/bathmatron/drugs.dm
  code/modules/cargo/packsrogue/merchant/luxury.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/roguetown/roguecrafting/alchemy/alch_cauldron_recipes.dm
  code/modules/roguetown/roguejobs/alchemist/container.dm
  code/modules/roguetown/roguemachine/drugmachine.dm
  icons/mob/screen_alert.dmi
  roguetown.dme
Labels: testmerged

#105 Bandit and Idol adjustments
  _maps/map_files/dun_manor/smalldecap.dmm
  _maps/map_files/dun_world/dun_world.dmm
  code/game/objects/effects/spawners/clutter_spawner.dm
  code/game/objects/structures/fluff.dm
  code/modules/clothing/rogueclothes/neck.dm
  code/modules/clothing/rogueclothes/storage.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/brigand.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/knave.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/roguemage.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/sawbones.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/sellsword.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/valuables.dm
  modular/Neu_Food/code/cookware/fork.dm
  modular/Neu_Food/code/cookware/platter.dm
  modular/Neu_Food/code/cookware/spoon.dm
  modular/code/game/objects/items/lewd/dildo.dm
Labels: testmerged, requires host approval

#127 Adds Ritualist virtue
  modular_azurepeak/virtues/utility.dm
Labels: testmerged, requires host approval

#98 resubmit of #92
  code/modules/jobs/job_types/roguetown/adventurer/wretch.dm
Labels: testmerged, requires host approval

#139 Pinning no longer has a passive stamina cost
  code/modules/mob/living/grabbing.dm
Labels: requires host approval

#116 Makes Etruscan Crossbowman not abysmal dogshit and a bandaid fix Grudgebearer
  code/modules/jobs/job_types/roguetown/mercenaries/classes/condottiero.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/grudgebearer.dm
Labels: requires host approval

#156 Stealth try 2
  code/__DEFINES/mob_timers.dm
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/_onclick/hud/screen_objects.dm
  code/_onclick/item_attack.dm
  code/datums/keybinding/living.dm
  code/datums/status_effects/rogue/debuff.dm
  code/game/objects/items/rogueitems/natural/clothfibersthorn.dm
  code/game/objects/items/rogueitems/natural/wood.dm
  code/game/objects/structures/roguewindow.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/npc/_npc.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/roguetownprocs.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/retaliate.dm
  code/modules/mob/living/simple_animal/rogue/rogueanimals.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/surgery/bodyparts/bodypart_wounds.dm
  modular_stonehedge/licensed-eaglephntm/LICENSE.md
  modular_stonehedge/licensed-eaglephntm/icons/mob/screen_alert.dmi
  modular_stonehedge/sound/mgsalert.ogg
Labels: testmerged

#154 Gives Wardens mediocre swords skill and Towner Hunters a hunting sword
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/hunter.dm
  code/modules/jobs/job_types/roguetown/garrison/bogguard.dm
Labels: testmerged

#125 Amazon subclass + makes kinis reapairable
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm
Labels: requires host approval

#122 removes blunt rework
  code/__DEFINES/combat.dm
  code/game/objects/items/rogueweapons/intents.dm
  code/game/objects/items/rogueweapons/melee/axes.dm
  code/game/objects/items/rogueweapons/melee/blunt.dm
  code/game/objects/items/rogueweapons/melee/flail.dm
  code/game/objects/items/rogueweapons/melee/knives.dm
  code/game/objects/items/rogueweapons/melee/polearms.dm
  code/game/objects/items/rogueweapons/melee/special.dm
  code/game/objects/items/rogueweapons/melee/swords.dm
  code/game/objects/items/rogueweapons/shields.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/wildshape/saiga.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/summons/summons_intents.dm
Labels: testmerged, requires host approval

#184 Hunky Wolf Humping Time (Now With Gock And Double Ds (and also flat fucks, for it is friday))
  code/datums/sexcon/sexcon.dm
  code/modules/antagonists/roguetown/villain/werewolf/werewolf.dm
  code/modules/antagonists/roguetown/villain/werewolf/werewolf_transformation.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/other/werewolf.dm
  icons/roguetown/mob/monster/werewolf.dmi
  icons/roguetown/mob/monster/werewolf_alt.dmi
  icons/roguetown/mob/monster/werewolf_dead.dmi
Labels: testmerged

#181 New Elf Skintone
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/elf/elfs.dm
Labels: testmerged

#180 Brings in a new tail + Bug head spritefix
  code/modules/client/customizer/customizers/organ/tail.dm
  code/modules/mob/dead/new_player/sprite_accessory/tails.dm
  icons/mob/sprite_accessory/snouts/snouts.dmi
  icons/mob/sprite_accessory/tails/tails.dmi
Labels: testmerged

#155 Buff acryne potential - Host Approved
  code/modules/spells/spell_types/wizard/buffs_debuffs/enlarge.dm
  code/modules/spells/spell_types/wizard/buffs_debuffs/fortitude.dm
  code/modules/spells/spell_types/wizard/buffs_debuffs/guidance.dm
  code/modules/spells/spell_types/wizard/buffs_debuffs/haste.dm
  code/modules/spells/spell_types/wizard/buffs_debuffs/hawks_eyes.dm
  code/modules/spells/spell_types/wizard/buffs_debuffs/leap.dm
  code/modules/spells/spell_types/wizard/buffs_debuffs/stoneskin.dm
  code/modules/spells/spell_types/wizard/misc/enchant_weapon.dm
  code/modules/spells/spell_types/wizard/projectiles_single/fetch.dm
  code/modules/spells/spell_types/wizard/projectiles_single/repel.dm
  modular_azurepeak/virtues/combat.dm
Labels: testmerged

#130 Minor Racial Job Restriction Rework
  code/__DEFINES/roguetown.dm
  code/controllers/subsystem/migrants.dm
  code/datums/migrants/migrant_role.dm
  code/datums/migrants/migrant_waves/heartfelt roles.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/roguetown/Inquisition/puritan.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/_advclass.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/hedgeknight.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/noble.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/heartfelt.dm
  code/modules/jobs/job_types/roguetown/church/druid.dm
  code/modules/jobs/job_types/roguetown/church/martyr.dm
  code/modules/jobs/job_types/roguetown/church/monk.dm
  code/modules/jobs/job_types/roguetown/church/priest.dm
  code/modules/jobs/job_types/roguetown/church/templar.dm
  code/modules/mob/dead/new_player/new_player.dm
Labels: testmerged, requires host approval

#175 Lunacy embracer wretch
  code/modules/jobs/job_types/roguetown/adventurer/types/wretch/lunacy_embracer.dm
  roguetown.dme
Labels: testmerged

#185 Fixes Fireball and Burn Damage from Fire
  code/controllers/subsystem/fire_burning.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/spells/spell_types/wizard/projectiles_aoe/fireball.dm
Labels: testmerged
